import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import type { Message } from "../api/client";
import { messageFixture } from "../test/fixtures";
import { AnswerProvenance } from "./AnswerProvenance";
import { StatusBanner } from "./StatusBanner";

function withProvenance(
  route: Message["route"],
  provenance: Partial<Message["provenance"]>,
): Message {
  return { ...messageFixture, route, provenance: { ...messageFixture.provenance, ...provenance } };
}

describe("AnswerProvenance", () => {
  it("explains the route, review expectation, and request ID for a hybrid answer", () => {
    render(<AnswerProvenance message={messageFixture} />);

    const group = screen.getByRole("group", { name: "How this answer was produced" });
    expect(group).toHaveTextContent("Combined criteria taken from your PDFs");
    expect(group).toHaveTextContent("a person should review the evidence before acting");
    expect(group).toHaveTextContent("appear in the generated SQL");
    expect(group).toHaveTextContent("literal-value match, not a check that the query logic is right");
    expect(group).toHaveTextContent("Request ID: req-fixture-0001");
  });

  it("states grounding warnings with counts and tells the reader not to rely on the answer", () => {
    render(
      <AnswerProvenance
        message={withProvenance("rag", {
          grounding_status: "warnings",
          invalid_citation_count: 2,
          unverified_quote_count: 1,
          criteria_provenance: "not_applicable",
        })}
      />,
    );

    const note = screen.getByText(/Grounding warning/);
    expect(note).toHaveTextContent("2 citation(s) point to sources that were not retrieved");
    expect(note).toHaveTextContent("1 quotation(s) were not found word-for-word");
    expect(note).toHaveTextContent("Do not rely on this answer");
  });

  it("flags an answer without any citation instead of implying it is grounded", () => {
    render(
      <AnswerProvenance
        message={withProvenance("rag", {
          grounding_status: "uncited",
          criteria_provenance: "not_applicable",
        })}
      />,
    );

    expect(screen.getByText(/cites no source/)).toBeVisible();
    expect(screen.queryByText(/found no problems/)).toBeNull();
  });

  it("warns when hybrid SQL ignores the extracted criteria or falls back to documents", () => {
    const { rerender } = render(
      <AnswerProvenance
        message={withProvenance("hybrid", { criteria_provenance: "unreferenced" })}
      />,
    );
    expect(screen.getByText(/does not mention the criteria/)).toBeVisible();

    rerender(
      <AnswerProvenance
        message={withProvenance("rag", { hybrid_fell_back_to_documents: true })}
      />,
    );
    expect(screen.getByText(/could not be safely turned into a table query/)).toBeVisible();
  });

  it("does not ask for evidence review of deterministic memory answers", () => {
    render(
      <AnswerProvenance
        message={withProvenance("memory", {
          grounding_status: "not_applicable",
          criteria_provenance: "not_applicable",
        })}
      />,
    );

    expect(screen.getByText(/not generated by a model/)).toBeVisible();
    expect(screen.queryByText(/Decision support only/)).toBeNull();
  });
});

describe("StatusBanner", () => {
  it("shows the correlation ID on errors and asks the user to quote it", () => {
    render(
      <StatusBanner kind="error" requestId="abc123">
        Something failed.
      </StatusBanner>,
    );

    const alert = screen.getByRole("alert");
    expect(alert).toHaveTextContent("Request ID: abc123");
    expect(alert).toHaveTextContent("quote this when asking for help");
    expect(alert).not.toHaveTextContent(/traceback|stack/i);
  });

  it("does not add the support hint to non-error banners", () => {
    render(
      <StatusBanner kind="success" requestId="abc123">
        Done.
      </StatusBanner>,
    );

    expect(screen.getByRole("status")).not.toHaveTextContent("quote this");
  });
});
