import type { Message } from "../api/client";

type Tone = "ok" | "warning" | "info";

export interface Note {
  tone: Tone;
  text: string;
}

const ROUTE_DESCRIPTIONS: Record<Message["route"], string> = {
  sql: "Answered from your uploaded table using a validated, read-only SQL query.",
  rag: "Answered from excerpts retrieved from your uploaded PDFs.",
  hybrid:
    "Combined criteria taken from your PDFs with your uploaded table. A model extracts the criteria and writes the query.",
  memory: "Answered from this session's saved analysis. The answer text was not generated by a model.",
  unsupported: "No matching table, document, or saved analysis was available for this question.",
};

export function describeRoute(route: Message["route"]): string {
  return ROUTE_DESCRIPTIONS[route];
}

export function groundingNote(message: Message): Note | null {
  const { provenance } = message;
  switch (provenance.grounding_status) {
    case "warnings": {
      const parts: string[] = [];
      if (provenance.invalid_citation_count > 0) {
        parts.push(
          `${provenance.invalid_citation_count} citation(s) point to sources that were not retrieved`,
        );
      }
      if (provenance.unverified_quote_count > 0) {
        parts.push(
          `${provenance.unverified_quote_count} quotation(s) were not found word-for-word in the sources`,
        );
      }
      return {
        tone: "warning",
        text: `Grounding warning: ${parts.join("; ")}. Do not rely on this answer until you have checked the sources.`,
      };
    }
    case "uncited":
      return {
        tone: "warning",
        text: "This answer cites no source. Check it against the retrieved excerpts before relying on it.",
      };
    case "checked_no_issues":
      return {
        tone: "info",
        text: "Citation and quotation checks found no problems. These checks confirm structure only; they do not prove the answer is correct.",
      };
    default:
      return null;
  }
}

export function criteriaNote(message: Message): Note | null {
  const { provenance } = message;
  if (provenance.hybrid_fell_back_to_documents) {
    return {
      tone: "warning",
      text: "The document guidance could not be safely turned into a table query, so only the document answer is shown.",
    };
  }
  switch (provenance.criteria_provenance) {
    case "unreferenced":
      return {
        tone: "warning",
        text: "The generated SQL does not mention the criteria extracted from your documents, so it may not apply the policy. Review the SQL before acting on these rows.",
      };
    case "excerpt_fallback":
      return {
        tone: "warning",
        text: "No structured criteria could be extracted, so the query was guided by raw excerpts. Verify that it reflects the policy.",
      };
    case "no_structured_criteria":
      return {
        tone: "info",
        text: "The documents contained no structured criteria to apply to the table.",
      };
    case "traced":
      return {
        tone: "info",
        text: "The extracted criteria appear in the generated SQL. This is a literal-value match, not a check that the query logic is right.",
      };
    default:
      return null;
  }
}
