"""Shared Streamlit session-state keys."""

UPLOADED_TABLE = "uploaded_table"
TABULAR_SIGNATURE = "tabular_signature"
UPLOAD_ERROR = "upload_error"
STORED_TABLE = "stored_table"
STORED_TABLE_SIGNATURE = "stored_table_signature"
CHAT_MESSAGES = "chat_messages"
DOCUMENT_RETRIEVER = "document_retriever"
DOCUMENT_STATUS = "document_status"
DOCUMENT_ERROR = "document_error"
DOCUMENT_SIGNATURE = "document_signature"
SESSION_MEMORY = "session_memory"
SESSION_ID = "session_id"
PDF_BYTES = "pdf_bytes"
PDF_SIGNATURE = "pdf_signature"
PROFILE_CACHE = "profile_cache"
ANALYSIS_CACHE = "analysis_cache"
ANOMALY_FEATURES = "anomaly_features"
ANOMALY_CONTAMINATION = "anomaly_contamination"
UPLOADER_GENERATION = "uploader_generation"
GEMINI_CONSENT_GIVEN = "gemini_consent_given"
